import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import UserSidebar from "../../components/UserSidebar";
import bg from "../../assets/images/bg.png";
import { apiUrl } from "../../config/runtime";

export default function UserSettings() {
  const [settings, setSettings] = useState({ notificationsEnabled: true, emailNotificationsEnabled: true, language: "en" });
  const [message, setMessage] = useState("");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token") || ""}` };
  useEffect(() => { fetch(apiUrl("/users/me"), { headers }).then(response => response.ok ? response.json() : null).then(user => user && setSettings({ notificationsEnabled: user.notifications_enabled !== false, emailNotificationsEnabled: user.email_notifications_enabled !== false, language: user.language || "en" })).catch(() => setMessage("Unable to load settings.")); }, []);
  const save = async event => { event.preventDefault(); const response = await fetch(apiUrl("/users/me"), { method: "PATCH", headers, body: JSON.stringify(settings) }); setMessage(response.ok ? "Settings saved." : "Unable to save settings. Please retry."); };
  return <main className="min-h-screen bg-cover bg-center bg-fixed p-4 pt-20 sm:p-6 sm:pt-6 lg:pl-72" style={{ backgroundImage: `linear-gradient(rgba(255,255,255,.72), rgba(255,255,255,.72)), url(${bg})` }}><UserSidebar /><section className="mx-auto max-w-2xl rounded-3xl border border-white/70 bg-white/85 p-7 shadow-xl backdrop-blur-2xl"><p className="text-xs font-bold uppercase tracking-wider text-sky-500">GlowCare account</p><h1 className="mt-1 text-3xl font-extrabold text-slate-800">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage notification delivery, language and account security.</p><form onSubmit={save} className="mt-7 space-y-5"><label className="block rounded-xl bg-pink-50 p-4 text-slate-700"><b>Preferred language</b><select value={settings.language} onChange={e => setSettings({ ...settings, language: e.target.value })} className="mt-2 w-full rounded-lg border border-pink-100 bg-white p-2"><option value="en">English</option><option value="te">Telugu</option><option value="hi">Hindi</option></select></label><label className="flex items-center justify-between rounded-xl bg-pink-50 p-4 text-slate-700"><span><b>App notifications</b><br /><small>Appointment, reminder and risk alerts</small></span><input type="checkbox" checked={settings.notificationsEnabled} onChange={e => setSettings({ ...settings, notificationsEnabled: e.target.checked })} /></label><label className="flex items-center justify-between rounded-xl bg-pink-50 p-4 text-slate-700"><span><b>Email notifications</b><br /><small>Daily and appointment reminder emails</small></span><input type="checkbox" checked={settings.emailNotificationsEnabled} onChange={e => setSettings({ ...settings, emailNotificationsEnabled: e.target.checked })} /></label><button className="w-full rounded-xl bg-gradient-to-r from-pink-500 to-sky-400 p-3 font-bold text-white">Save settings</button></form><Link to="/forgot-password" className="mt-5 inline-block rounded-xl bg-sky-50 px-4 py-2 font-semibold text-sky-700">Change password with email OTP</Link>{message && <p className="mt-4 rounded-xl bg-sky-50 p-3 text-sm text-sky-700">{message}</p>}</section></main>;
}
